export const CALCULATE_PERCENTAGE = 'CALCULATE_PERCENTAGE';

export const SWITCH_SHOW_DONE = 'SWITCH_SHOW_DONE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const UPDATE_DATA = 'UPDATE_DATA';

export const UPDATE_ITEMS = 'UPDATE_ITEMS';

export const ADD_ITEM = 'ADD_ITEM';

export const SHOW_DETAILS = 'SHOW_DETAILS';

export const CLOSE_DETAILS = 'CLOSE_DETAILS';

export const CHANGE_CATEGORY_FOR_TASK = 'CHANGE_CATEGORY_FOR_TASK';
