export const CALCULATE_PERCENTAGE = 'CALCULATE_PERCENTAGE';

export const SWITCH_SHOW_DONE = 'SWITCH_SHOW_DONE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const UPDATE_DATA = 'UPDATE_DATA';

export const RERENDER_ITEMS = 'RERENDER_ITEMS';